export const FETCH_FOLDERS = "FETCH_FOLDERS";
export const FETCH_FILES = "FETCH_FILES";
export const FILE_SELECTED = "FILE_SELECTED";
export const FETCH_SELECTED_FILE_METADATA = "FETCH_SELECTED_FILE_METADATA";
export const GAIN_VALUE_CHANGED = "GAIN_VALUE_CHANGED";
export const ENVELOPES_VALUE_CHANGED = "ENVELOPES_VALUE_CHANGED";
export const ATTACK_VALUE_CHANGED = "ATTACK_VALUE_CHANGED";
export const HOLD_VALUE_CHANGED = "HOLD_VALUE_CHANGED";
export const DECAY_VALUE_CHANGED = "DECAY_VALUE_CHANGED";
export const FILTERS_VALUE_CHANGED = "FILTERS_VALUE_CHANGED";
export const CUTOFF_VALUE_CHANGED = "CUTOFF_VALUE_CHANGED";
export const RESO_VALUE_CHANGED = "RESO_VALUE_CHANGED";
export const FX_VALUE_CHANGED = "FX_VALUE_CHANGED";
export const REVERB_VALUE_CHANGED = "REVERB_VALUE_CHANGED";
export const DELAY_VALUE_CHANGED = "DELAY_VALUE_CHANGED";
export const UPDATE_METADATA = "UPDATE_METADATA";
export const FETCH_SELECTED_SAMPLE_DATA = "FETCH_SELECTED_SAMPLE_DATA";
export const CREATE_FOLDER = "CREATE_FOLDER";
export const GENERATE_NEW_FILE = "GENERATE_NEW_FILE";
export const SAVE_THE_NEWLY_GENERATED_FILE = "SAVE_THE_NEWLY_GENERATED_FILE";
// auth
export const AUTHENTICATED = "authenticated_user";
export const UNAUTHENTICATED = "unauthenticated_user";
export const AUTHENTICATION_ERROR = "authentication_error";
export const USER_LOGOUT = "USER_LOGOUT";
// admin
export const FETCH_JOBS = "FECTH_JOBS";
export const POST_NEW_GENERATOR_MODEL = "CREATE_NEW_GENERATOR_MODEL";
// user
export const CREATE_USER = "CREATE_USER";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
